import html2pdf from "html2pdf.js";

export default function exportPdf(messageContent, userQuestion) {
  const container = document.createElement("div");
  container.style.fontFamily = "'DM Sans', sans-serif";
  container.style.padding = "32px";
  container.style.color = "#1a1a1a";
  container.style.lineHeight = "1.8";
  container.style.maxWidth = "700px";

  container.innerHTML = `
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #c9a84c;">
      <div style="width:40px;height:40px;background:#c9a84c;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:20px;">⚖</div>
      <div>
        <h1 style="margin:0;font-size:22px;font-family:'Playfair Display',serif;color:#1a1a1a;">NyayBot</h1>
        <p style="margin:0;font-size:11px;color:#666;">AI Legal Aid for India</p>
      </div>
    </div>

    ${userQuestion ? `
      <div style="background:#f5f0e8;border-radius:10px;padding:14px 18px;margin-bottom:20px;">
        <p style="margin:0 0 4px 0;font-size:11px;font-weight:600;color:#888;text-transform:uppercase;letter-spacing:1px;">Your Question</p>
        <p style="margin:0;font-size:14px;color:#1a1a1a;">${userQuestion}</p>
      </div>
    ` : ""}

    <div style="font-size:14px;color:#1a1a1a;white-space:pre-wrap;">${messageContent}</div>

    <div style="margin-top:32px;padding-top:16px;border-top:1px solid #ddd;font-size:11px;color:#888;">
      <p style="margin:0;">⚠ Disclaimer: This is general legal information, not legal advice. For serious matters, please consult a qualified lawyer.</p>
      <p style="margin:6px 0 0 0;">Generated by NyayBot · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>
    </div>
  `;

  html2pdf()
    .set({
      margin: [10, 10, 10, 10],
      filename: `NyayBot-Response-${Date.now()}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    })
    .from(container)
    .save();
}
