import html2pdf from "html2pdf.js";
import { parseMarkdown } from "./markdown";

/**
 * Exports one or all chat messages as a styled PDF.
 * @param {string|null} singleContent - Single AI message content (null for full chat)
 * @param {string|null} userQuestion - The user question preceding the response
 * @param {Array|null} allMessages - Full message history for full-chat export
 * @param {string} chatTitle - Chat title override
 */
export default function exportPdf(singleContent, userQuestion, allMessages = null, chatTitle = "NyayBot Legal Analysis") {
  const isFullChat = Array.isArray(allMessages) && allMessages.length > 0;

  const container = document.createElement("div");
  container.style.fontFamily = "'DM Sans', sans-serif";
  container.style.color = "#1a1a1a";
  container.style.lineHeight = "1.8";
  container.style.maxWidth = "700px";
  container.style.margin = "0 auto";

  // Build header
  const header = `
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:28px;padding-bottom:16px;border-bottom:3px solid #c9a84c;">
      <div style="width:44px;height:44px;background:#c9a84c;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px;">⚖</div>
      <div>
        <h1 style="margin:0;font-size:22px;font-weight:700;color:#1a1a1a;">${chatTitle}</h1>
        <p style="margin:0;font-size:11px;color:#888;">Generated by NyayBot · AI Legal Aid for India · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>
      </div>
    </div>
  `;

  // Build body content
  let body = "";

  if (isFullChat) {
    // Full chat export: render all messages
    allMessages.forEach((msg, index) => {
      if (msg.role === "user") {
        body += `
          <div style="page-break-inside:avoid;margin-bottom:20px;break-inside:avoid;">
            <div style="background:#f5f0e8;border-radius:10px;padding:14px 18px;">
              <p style="margin:0 0 4px 0;font-size:10px;font-weight:700;color:#888;text-transform:uppercase;letter-spacing:1px;">Your Question</p>
              <p style="margin:0;font-size:14px;color:#1a1a1a;">${msg.content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>
            </div>
          </div>
        `;
      } else if (msg.role === "assistant") {
        body += `
          <div style="page-break-inside:avoid;margin-bottom:28px;break-inside:avoid;">
            <div style="background:#fafafa;border-left:3px solid #c9a84c;border-radius:0 10px 10px 0;padding:16px 20px;">
              <p style="margin:0 0 10px 0;font-size:10px;font-weight:700;color:#c9a84c;text-transform:uppercase;letter-spacing:1px;">NyayBot Analysis</p>
              <div style="font-size:14px;color:#1a1a1a;line-height:1.8;">
                ${renderPdfMarkdown(msg.content)}
              </div>
            </div>
          </div>
        `;
      }
    });
  } else {
    // Single response export
    if (userQuestion) {
      body += `
        <div style="page-break-inside:avoid;margin-bottom:20px;break-inside:avoid;">
          <div style="background:#f5f0e8;border-radius:10px;padding:14px 18px;">
            <p style="margin:0 0 4px 0;font-size:10px;font-weight:700;color:#888;text-transform:uppercase;letter-spacing:1px;">Your Question</p>
            <p style="margin:0;font-size:14px;color:#1a1a1a;">${userQuestion.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>
          </div>
        </div>
      `;
    }
    body += `
      <div style="page-break-inside:avoid;break-inside:avoid;">
        <div style="font-size:14px;color:#1a1a1a;line-height:1.8;">
          ${renderPdfMarkdown(singleContent)}
        </div>
      </div>
    `;
  }

  // Disclaimer always at the very end
  const disclaimer = `
    <div style="margin-top:40px;padding-top:16px;border-top:1px solid #ddd;font-size:11px;color:#999;">
      <p style="margin:0;">⚠ Disclaimer: This document contains general legal information, not legal advice. For serious legal matters, please consult a qualified lawyer or advocate.</p>
      <p style="margin:4px 0 0 0;">Generated by NyayBot · For personal reference only · Not for official court use.</p>
    </div>
  `;

  container.innerHTML = `<div style="padding:32px;">${header}${body}${disclaimer}</div>`;

  const filename = isFullChat
    ? `NyayBot-Full-Chat-${Date.now()}.pdf`
    : `NyayBot-Response-${Date.now()}.pdf`;

  html2pdf()
    .set({
      margin: [8, 8, 8, 8],
      filename,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, scrollY: 0 },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      pagebreak: { mode: ["avoid-all", "css", "legacy"] },
    })
    .from(container)
    .save();
}

/**
 * Converts markdown to PDF-safe HTML with inline styles.
 * avoids CSS class dependencies and ensures bold/italic works in pdf.
 */
function renderPdfMarkdown(text) {
  if (!text) return "";

  let html = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    // Horizontal rules
    .replace(/^---+$/gm, '<hr style="border:none;border-top:1px solid #ddd;margin:12px 0;" />')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong style="font-weight:700;color:#1a1a1a;">$1</strong>')
    // Italic (single *) 
    .replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, '<em>$1</em>')
    // Headings (# H1, ## H2)
    .replace(/^### (.+)$/gm, '<p style="font-size:14px;font-weight:700;margin:14px 0 4px 0;color:#333;">$1</p>')
    .replace(/^## (.+)$/gm, '<p style="font-size:15px;font-weight:700;margin:16px 0 6px 0;color:#1a1a1a;">$1</p>')
    .replace(/^# (.+)$/gm, '<p style="font-size:17px;font-weight:700;margin:18px 0 8px 0;color:#1a1a1a;">$1</p>')
    // Numbered list items
    .replace(/^(\d+)\.\s+(.+)$/gm, '<div style="display:flex;gap:8px;margin:4px 0;"><span style="font-weight:700;min-width:20px;">$1.</span><span>$2</span></div>')
    // Bullet list items
    .replace(/^[-•]\s+(.+)$/gm, '<div style="display:flex;gap:8px;margin:4px 0;"><span style="color:#c9a84c;min-width:14px;">•</span><span>$1</span></div>')
    // Paragraphs / line breaks
    .replace(/\n\n/g, '</p><p style="margin:10px 0;">')
    .replace(/\n/g, "<br />");

  return `<p style="margin:0;">${html}</p>`;
}
